// LOGIN
export const IS_LOGIN = 'IS_LOGIN';
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// GET IMAGE FROM FIRESTORE
export const GET_PROMOTION = 'GET_PROMOTION';
export const GET_PROMOTION_SUCCESS = 'GET_PROMOTION_SUCCESS';
export const GET_PROMOTION_FAILED = 'GET_PROMOTION_FAILED';

// GET CATEGORY FROM FIRESTORE
export const GET_CATEGORY_PERSON = 'GET_CATEGORY_PERSON';
export const GET_CATEGORY_PERSON_SUCCESSFULLY = 'GET_CATEGORY_PERSON_SUCCESSFULLY';
export const GET_CATEGORY_PERSON_FAILED = 'GET_CATEGORY_PERSON_FAILED';

// GET LIST PERSON FROM FIRESTORE
export const LIST_PERSON = 'LIST_PERSON';
export const LIST_PERSON_SUCCESSFULLY = 'LIST_PERSON_SUCCESSFULLY';
export const LIST_PERSON_FAILED = 'LIST_PERSON_FAILED';

// GET PERSON FOR HOME
export const GET_PERSON_HOME = 'GET_PERSON_HOME';
export const GET_PERSON_HOME_SUCCESSFULLY = 'GET_PERSON_HOME_SUCCESSFULLY';
export const GET_PERSON_HOME_FAILED = 'GET_PERSON_HOME_FAILED';

// ADD PERSON TO FIRESTORE
export const ADD_PERSON = 'ADD_PERSON';
export const ADD_PERSON_SUCCESSFULLY = 'ADD_PERSON_SUCCESSFULLY';
export const ADD_PERSON_FAILED = 'ADD_PERSON_FAILED';

// UPDATE PERSON TO FIRESTORE
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const UPDATE_PERSON_SUCCESSFULLY = 'UPDATE_PERSON_SUCCESSFULLY';
export const UPDATE_PERSON_FAILED = 'UPDATE_PERSON_FAILED';

// DELETE PERSON TO FIRESTORE
export const DELETE_PERSON = 'DELETE_PERSON';
export const DELETE_PERSON_SUCCESSFULLY = 'DELETE_PERSON_SUCCESSFULLY';
export const DELETE_PERSON_FAILED = 'DELETE_PERSON_FAILED';

// GET LIST GIFT
export const LIST_GIFT = 'LIST_GIFT';
export const LIST_GIFT_SUCCESS = 'LIST_GIFT_SUCCESS';
export const LIST_GIFT_FAILED = 'LIST_GIFT_FAILED';

// GET LIST NOCTICE
export const LIST_NOTICE = 'LIST_NOTICE';
export const LIST_NOTICE_SUCCESS = 'LIST_NOTICE_SUCCESS';
export const LIST_NOTICE_FAILED = 'LIST_NOTICE_FAILED';

// ADD USER
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESSFULLY = 'ADD_USER_SUCCESSFULLY';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';

// UPDATE GIFT DETAIL
export const UPDATE_GIFT_DETAIL = 'UPDATE_GIFT_DETAIL';
export const UPDATE_GIFT_DETAIL_SUCCESS = 'UPDATE_GIFT_DETAIL_SUCCESS';
export const UPDATE_GIFT_DETAIL_FAILED = 'UPDATE_GIFT_DETAIL_FAILED';

// DELETE GIFT DETAIL
export const DELETE_GIFT_DETAIL = 'DELETE_GIFT_DETAIL';
export const DELETE_GIFT_DETAIL_SUCCESS = 'DELETE_GIFT_DETAIL_SUCCESS';
export const DELETE_GIFT_DETAIL_FAILED = 'DELETE_GIFT_DETAIL_FAILED';

// GET LIST RECOMMENDED
export const RECOMMENDED_GIFT = 'RECOMMENDED_GIFT';
export const RECOMMENDED_GIFT_SUCCESS = 'RECOMMENDED_GIFT_SUCCESS';
export const RECOMMENDED_GIFT_FAILED = 'RECOMMENDED_GIFT_FAILED';

// REGISTRATION GIFT
export const PERSON_ITEM = 'PERSON_ITEM';
export const GIFT_REGISTRATION = 'GIFT_REGISTRATION';
export const GIFT_REGISTRATION_SUCCESSFULLY = 'GIFT_REGISTRATION_SUCCESSFULLY';
export const GIFT_REGISTRATION_FAILED = 'GIFT_REGISTRATION_FAILED';

// GET COLUMN
export const GET_COLUMN = 'GET_COLUMN';
export const GET_COLUMN_SUCCESSFULLY = 'GET_COLUMN_SUCCESSFULLY';
export const GET_COLUMN_FAILED = 'GET_COLUMN_FAILED';

// GET PECIPE
export const GET_RECIPE = 'GET_RECIPE';
export const GET_RECIPE_SUCCESSFULLY = 'GET_RECIPE_SUCCESSFULLY';
export const GET_RECIPE_FAILED = 'GET_RECIPE_FAILED';

// GET USER
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESSFULLY = 'GET_USER_SUCCESSFULLY';
export const GET_USER_FAILED = 'GET_USER_FAILED';

// UPDATE USER
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESSFULLY = 'UPDATE_USER_SUCCESSFULLY';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

// GET NOTICE FOR HOME
export const GET_NOTICE_HOME = 'GET_NOTICE_HOME';
export const GET_NOTICE_HOME_SUCCESSFULLY = 'GET_NOTICE_HOME_SUCCESSFULLY';
export const GET_NOTICE_HOME_FAILED = 'GET_NOTICE_HOME_FAILED';

// GET COLUMN OR RECIPE FOR HOME
export const GET_COLUMN_OR_RECIPE_HOME = 'GET_COLUMN_OR_RECIPE_HOME';
export const GET_COLUMN_OR_RECIPE_HOME_SUCCESSFULLY = 'GET_COLUMN_OR_RECIPE_HOME_SUCCESSFULLY';
export const GET_COLUMN_OR_RECIPE_HOME_FAILED = 'GET_COLUMN_OR_RECIPE_HOME_FAILED';

// GET DATA FOR PUSH NOTIFICATION
export const GET_DATA_NOTIFICATION = 'GET_DATA_NOTIFICATION';
export const GET_DATA_NOTIFICATION_SUCCESSFULLY = 'GET_DATA_NOTIFICATION_SUCCESSFULLY';
export const GET_DATA_NOTIFICATION_FAILED = 'GET_DATA_NOTIFICATION_FAILED';